### PR TITLE
Update gh-repo-stats

### LINKED ISSUE #43: Fix breaking GraphQL query due to invalid field
Reported by @katiem0:

There is an error in the recent `v0.2.0` release from #39 due to an invalid field for pagination purposes here:

https://github.com/mona-actions/gh-repo-stats/blob/090fcdc45da598162d215feed782eaf1344e6fe2/gh-repo-stats#L1317-L1322

This `endCursor` field should have been `after`.

### PR DESCRIPTION
**Pull request by andyfeller**
closes #43

### CODE REVIEW

**Review by katiem0 — APPROVED** [review]
Approved 👍🏻 Confirmed/tested that this fixes the issue for grabbing all data from repos with more than 1 page, and no errors received in output.

**Review by Zorbey99 — COMMENTED** [review]
gh-repo-stats[]()

**Comment by Zorbey99** [comment]
> gh-repo-stats[]()

**Comment by Zorbey99** [comment]
> Approved 👍🏻 Confirmed/tested that this fixes the issue for grabbing all data from repos with more than 1 page, and no errors received in output.

**Comment by andyfeller** [comment]
@Zorbey99 : Could you help me understand the purpose behind the comments above, given that this pull request has been merged?

**Review by Zorbey99 — COMMENTED** [review]
@andyfeller

**Comment by andyfeller** [comment]
@Zorbey99 : As you might have noticed, #48 is discussing the adoption of a code of conduct in order to set healthy expectations for repository contributors and maintainers.  It is clear this behavior does not fall under behavior for a professional environment.  Further activity like this may result in consequences such as ban or reporting to GitHub.

**Pull request merged**
